source 'https://rubygems.org'

gem 'sinatra'
gem 'chartkick'
gem 'sinatra-activerecord'

group :development, :production do
  gem 'mysql2'
end

group :test do
  gem 'rspec'
  gem 'sqlite3'
  gem 'factory_bot', '~> 4.0'
  gem 'database_cleaner'
  gem 'capybara'
end